name: Deploy to Docker Hub

on:
workflow_run:
workflows: ["CI Pipeline"]
types:
-completed

jobs:
  deploy:
    runs-on: self-hosted  # Use your self-hosted runner

    steps:
   - name: Pull Docker image
    run: sudo docker pull rajendrabaneshi/project-1:latest
  - name: Delete Old docker container
    run: sudo docker rm -f project-1-container || true
  - name: Run Docker Container
    run: sudo docker run -d -p 8080:8080 --name project-1-container rajendrabaneshi/project-1 
   
