name: Deploy to Docker Hub

on:
  push:
    branches:
      - main  # Adjust this branch name if needed

jobs:
  deploy:
    runs-on: self-hosted  # Use your self-hosted runner

    steps:
   - name: Pull Docker image
    run: sudo docker pull rajendrabaneshi/project-1:latest
  - name: Delete Old docker container
    run: sudo docker rm -f project-1-container || true
  - name: Run Docker Container
    run: sudo docker run -d -p 8080:8080 --name project-1-container rajendrabaneshi/project-1 
   
