name: Deploy to Production

on:
  push:
    branches:
      - main # Adjust this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t rajendrabaneshi/project-2:latest .

    - name: Log in to Docker Hub (or your container registry)
      run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Push Docker image
      run: docker push  rajendrabaneshi/project-2:latest

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: SSH into Production Server
      uses: appleboy/ssh-action
      with:
        host: ${{ secrets.PRODUCTION_SERVER_HOST }}
        username: ${{ secrets.PRODUCTION_SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PRODUCTION_SERVER_PORT }} # Change to your server's SSH port if needed

    - name: Pull and Run Docker Image
      run: |
        docker pull  rajendrabaneshi/project-2:latest
        docker run -d --name project-1-container -p 80:80 project-2:latest
